void first_over(FILE *);
void second_over(FILE *);
int isLabel(char *);
int isCommand(char *,int *);
int isRegister(char *,int *);
int isGuidStmt(char *); 
int isDataGuid(char *);
int isEntryGuid(char *);
int isExtrnGuid(char *);
int isCorrectLabel(char *);
int isCorrectDynamicPrm(char *);
void add_data(char *);
void add_string(void);
void add_DC_table(int );
void print_DC_table(void);
void add_guid_stmt(char *);
void add2list(pSymbol * ,char *,int ,enum ECD );
unsigned int get_address(pSymbol ,char *);
unsigned int get_status(pSymbol ,char *);
void print_list(pSymbol);
void free_list(pSymbol *); 
void cal_num_word(int);
int isCorrectNumber(char *);
int isLabelExists(char *);
int check_dest_op(char *,int,Address_Method *);
int check_source_op(char *,int,Address_Method *);
int isExists(pSymbol ,char *);
int check_method(Address_Method ,char *);
void update_address(pSymbol);
void add_DC_table2mem();
void build_word(int);
void decode_second_word(char *,int,Address_Method,int);
unsigned int get_dynamic_num(int,int,char *);
void write_table2file(pLabel,int,char *,char *);
void write_mem2file(char *,char *);
void get_special_code_address(int,char *);
void get_special_code(int ,char *);


extern Op_Code op_code[];
extern Registers registers[];
extern int DC,IC;
extern pData t_data;
extern int err_count;
extern pSymbol head;
extern int mem_word[MEMORY_SIZE];
extern int line_number;
extern pLabel ext_table,ent_table;
extern int inx_ent,inx_ext;
extern char SpecialCode[];
